// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNXpfpW5zLeY-wkqA9Yxo-BflaadonHYs',
    appId: '1:357067677157:web:09b0adc4cf8cb579c5a30c',
    messagingSenderId: '357067677157',
    projectId: 'hkili-286e1',
    authDomain: 'hkili-286e1.firebaseapp.com',
    storageBucket: 'hkili-286e1.appspot.com',
    measurementId: 'G-ZZ4Y8F46M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCILOm2tZ2n4_L__j7IrMSuRwGFjxdjruU',
    appId: '1:357067677157:android:bfa0a1b9ad89af37c5a30c',
    messagingSenderId: '357067677157',
    projectId: 'hkili-286e1',
    storageBucket: 'hkili-286e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjLKXV_QRJiCSoFzYTt4obuEkPW_djPoA',
    appId: '1:357067677157:ios:396b5d35d3fe10acc5a30c',
    messagingSenderId: '357067677157',
    projectId: 'hkili-286e1',
    storageBucket: 'hkili-286e1.appspot.com',
    iosClientId:
        '357067677157-00f6jru42ruqcvodlr8osr4kvcenbcq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hkili',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjLKXV_QRJiCSoFzYTt4obuEkPW_djPoA',
    appId: '1:357067677157:ios:396b5d35d3fe10acc5a30c',
    messagingSenderId: '357067677157',
    projectId: 'hkili-286e1',
    storageBucket: 'hkili-286e1.appspot.com',
    iosClientId:
        '357067677157-00f6jru42ruqcvodlr8osr4kvcenbcq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hkili',
  );
}
